/* =============================================================================
 * KASAUTI — engine/analyzer.ts
 * -----------------------------------------------------------------------------
 * WHAT:  The single entry point that turns (path, language, text) into a
 *        FileAnalysis. Decides the tier, runs the right analysis, and never
 *        throws for "normal" problems (it degrades gracefully instead).
 * WHY:   Workers, tests, and future CLI tools all call this one function, so
 *        the tier rules in SPEC §A7.2 and edge cases in §A9 live in ONE place.
 * FLOW:  worker.ts -> analyze() -> [metrics.ts | generic.ts] -> FileAnalysis
 *        -> worker posts it back to the host (workerPool.ts)
 * ========================================================================== */

import { analyzeTier1, CursorLike } from './metrics';
import { analyzeTier2 } from './generic';
import { getSpec, tier2Info, SyntaxNode } from './languages';
import { GrammarError, ParserService } from './parser';
import type { FileAnalysis, Tier } from './types';

/** Bump when metric definitions change -> invalidates every cache entry. */
export const ENGINE_VERSION = '1.0.0';

const GENERATED_HEADER = /auto-?generated|do not edit|@generated|generated by/i;
const GENERATED_PATH = /(\.min\.(js|css)$)|(\.pb\.go$)|(_pb2(_grpc)?\.py$)|(\.g\.dart$)|(\.freezed\.dart$)|(\.designer\.cs$)|(\.generated\.\w+$)/i;

/** Tier 3 result: nothing measured, only a reason. Also used by the host for
 *  files it refuses to read (binary, too large). */
export function skipped(languageKey: string, reason: string, lines = 0): FileAnalysis {
  return {
    engineVersion: ENGINE_VERSION, languageKey, tier: 3, skipReason: reason,
    lines, sloc: 0, commentLines: 0, functions: [], classes: [], todos: [], lineLengths: new Uint32Array(0),
    hasSyntaxErrors: false, tokenIds: new Uint32Array(0), tokenLines: new Uint32Array(0), analysisMs: 0,
  };
}

/** Minified = huge average line length, or one giant line (SPEC §A9). */
function looksMinified(text: string): boolean {
  if (text.length < 2000) return false;
  const lines = text.split('\n');
  const avg = text.length / lines.length;
  return avg > 500 || lines.some((l) => l.length > 5000);
}

/** Jupyter notebook -> concatenated code cells + a map back to cell numbers.
 *  WHY: students use notebooks heavily (OD-6 decided: analyze code cells). */
function notebookToPython(text: string): { code: string; cellOfLine: number[] } | undefined {
  try {
    const nb = JSON.parse(text) as { cells?: Array<{ cell_type: string; source: string | string[] }> };
    const out: string[] = [];
    const cellOfLine: number[] = [];
    (nb.cells ?? []).forEach((cell, idx) => {
      if (cell.cell_type !== 'code') return;
      const src = Array.isArray(cell.source) ? cell.source.join('') : cell.source;
      // IPython magics (%timeit, !pip) are not Python; comment them out.
      for (const line of src.split('\n')) {
        out.push(/^\s*[%!]/.test(line) ? '# ' + line : line);
        cellOfLine.push(idx + 1);
      }
    });
    return { code: out.join('\n'), cellOfLine };
  } catch { return undefined; }
}

/**
 * Analyze one file.
 * @param languageKey  from languages.detectLanguage()
 * @param filePath     used only for generated-file detection
 */
export async function analyze(parser: ParserService, languageKey: string, filePath: string, text: string, forceGeneric = false): Promise<FileAnalysis> {
  const t0 = Date.now();
  const lineCount = text.split('\n').length;

  // ---- Tier 3 gates -------------------------------------------------------
  if (GENERATED_PATH.test(filePath)) return skipped(languageKey, 'generated', lineCount);
  const header = text.split('\n', 5).join('\n');
  if (GENERATED_HEADER.test(header)) return skipped(languageKey, 'generated', lineCount);
  if (looksMinified(text)) return skipped(languageKey, 'minified', lineCount);

  // ---- Notebooks: analyze code cells as Python ----------------------------
  let source = text;
  let grammarKey = languageKey;
  let notebookCells: number[] | undefined;
  if (languageKey.startsWith('notebook:')) {
    const nb = notebookToPython(text);
    if (!nb) return skipped(languageKey, 'invalid notebook', lineCount);
    source = nb.code;
    grammarKey = 'python';
    notebookCells = nb.cellOfLine;
  }

  // ---- Tier 1: full AST analysis -----------------------------------------
  let fallbackNote: string | undefined;
  if (getSpec(grammarKey) && !parser.isBroken(grammarKey) && !forceGeneric) {
    const lines = source.split('\n').length;
    let tree;
    try {
      tree = await parser.parse(grammarKey, source);
      const cursor = tree.walk();
      try {
        const m = analyzeTier1(tree.rootNode as unknown as SyntaxNode, cursor as unknown as CursorLike, grammarKey, lines);
        const result: FileAnalysis = {
          engineVersion: ENGINE_VERSION, languageKey, tier: 1 as Tier,
          lines, sloc: m.sloc, commentLines: m.commentLines,
          functions: m.functions, classes: m.classes, todos: m.todos,
          lineLengths: Uint32Array.from(source.split(/\r?\n/), (l) => l.length),
          hasSyntaxErrors: tree.rootNode.hasError,
          tokenIds: m.tokenIds, tokenLines: m.tokenLines,
          analysisMs: Date.now() - t0,
        };
        if (notebookCells) {
          // Positions refer to concatenated cells; rename functions with their
          // cell so the user can find them ("load_data (cell 3)").
          for (const f of result.functions) f.name += ` (cell ${notebookCells[f.startLine] ?? '?'})`;
          result.fallbackNote = 'Notebook: line numbers refer to the combined code cells.';
        }
        return result;
      } finally {
        cursor.delete();
      }
    } catch (e) {
      if (e instanceof GrammarError) {
        // Re-throw so the worker can tell the host to recycle it (runtime may be corrupt).
        throw e;
      }
      fallbackNote = `Full analysis failed (${String((e as Error)?.message ?? e)}); showing partial analysis.`;
    } finally {
      tree?.delete();
    }
  } else if (getSpec(grammarKey)) {
    fallbackNote = `The ${grammarKey} parser failed to load on this machine; showing partial analysis.`;
  }

  // ---- Tier 2: generic analysis --------------------------------------------
  const info = tier2Info(languageKey.startsWith('tier2:') ? languageKey : 'tier2:' + grammarKey);
  const g = analyzeTier2(source, info.comments, languageKey);
  return {
    engineVersion: ENGINE_VERSION, languageKey, tier: 2,
    lines: g.lines, sloc: g.sloc, commentLines: g.commentLines,
    functions: [], classes: [], todos: g.todos, lineLengths: g.lineLengths,
    indentNesting: g.indentNesting, hasSyntaxErrors: false,
    tokenIds: g.tokenIds, tokenLines: g.tokenLines,
    analysisMs: Date.now() - t0, fallbackNote,
  };
}
